[package]
name = "client"
version.workspace = true
edition.workspace = true

[dependencies]
fluent.workspace = true
noiz.workspace = true
bevy.workspace = true
avian3d.workspace = true
bevy_skein.workspace = true
bevy_enhanced_input.workspace = true
bevy_asset_loader.workspace = true
bevy_hanabi.workspace = true
bevy_replicon.workspace = true
bevy_replicon_quinnet.workspace = true
bevy_quinnet.workspace = true
polyanya.workspace = true
rerecast.workspace = true
bevy_mod_outline.workspace = true
bevy_vello.workspace = true
bevy_seedling.workspace = true
audionimbus.workspace = true
chill_bevy_console.workspace = true
shared = { path = "../shared" }
bevy_simple_text_input = "0.15.0"
futures-lite = "2.6.1"
