[package]
name = "prototype_19"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.19.0", path = "../bevy", features = [
	"basis-universal",
	"ktx2",
	"bevy_dev_tools",
] }
avian3d = { path = "../avian/crates/avian3d", features = ["simd"] }
bevy_skein = { path = "../skein" }
bevy_enhanced_input = { path = "../bevy_enhanced_input" }

fluent = "0.17.0"
noiz = "0.5.0"
