[package]
name = "prototype_19"
version = "0.1.0"
edition = "2024"

[dependencies]


# bevy = { version = "0.19.0", path = "../bevy", features = [ "basis-universal", "ktx2", "bevy_dev_tools" ] }
# avian3d = { path = "../avian/crates/avian3d", features = ["simd"] }
# bevy_skein = { path = "../skein" }
# bevy_enhanced_input = { path = "../bevy_enhanced_input" }
# bevy_asset_loader = { path = "../bevy_asset_loader/bevy_asset_loader" }
# bevy_hanabi = { path = "../bevy_hanabi" }

# audionimbus = { path = "../audionimbus/audionimbus", features = ["auto-install"] }

# avian3d = { path = "../avian/crates/avian3d", features = ["simd"] }
# bevy_skein = { path = "../skein" }
# bevy_enhanced_input = { path = "../bevy_enhanced_input" }
# bevy_asset_loader = { path = "../bevy_asset_loader/bevy_asset_loader" }
# bevy_hanabi = { path = "../bevy_hanabi" }

fluent = "0.17.0"
noiz = "0.5.0"
rand = "0.10.1"

bevy = { version = "0.19.0", features = [
	"basis-universal",
	"ktx2",
	"bevy_dev_tools",
] }
avian3d = { version = "0.7.0", features = ["simd"] }
bevy_skein = "0.6.0"
bevy_enhanced_input = "0.26.0"
bevy_asset_loader = "0.27.0"
bevy_hanabi = "0.19.0"
bevy_seedling = { path = "../bevy_seedling" }
