//! The player input protocol: a BEI context + ahoy action types, replicated via
//! `lightyear_inputs_bei`.
//!
//! This is the M2 "idiomatic" flow (see `docs/agents/adr/0005`'s follow-up plan): the **server**
//! spawns the input context + its action entities as part of the player bundle (`player()`),
//! they replicate to the owning client (via `ActionOf<C>`'s hierarchy sender), the owning
//! client adds local-only `Bindings` to the replicated action entities (see
//! `controls.rs`'s binding observers), and from then on the client's BEI action state streams
//! to the server as `BEIStateSequence` messages, which mock the server-side actions — so
//! ahoy's observers fire on **both** sides and both run the same KCC over the same input.
//!
//! lightyear's `PredictionPlugin` hard-depends on one of its input plugins
//! (`lightyear_inputs_native`/`_bei`/`_leafwing`) having initialized `LastConfirmedInput` —
//! without one, the client panics ("Resource does not exist: LastConfirmedInput") the moment
//! a connection starts. Registering [`InputPlugin`] here satisfies that (with the
//! `input_bei` meta-crate feature — see the root `Cargo.toml` comment).
//!
//! This lives in `shared`, not either binary, for the same reason `replication.rs` does: the
//! input protocol (`BEIStateSequence<C>` messages, replicated context/action entities) is
//! network state both sides must agree on. Each binary enables its own `client`/`server`
//! feature on the `lightyear_inputs_bei` dependency; feature unification applies whichever
//! subset is active to this crate's build.
//!
//! **Look is client-owned input** (ADR 0017): the owning client sends its absolute camera
//! direction as the [`Look`] action every tick, in the same input stream as movement. Both
//! sides apply it with [`apply_look`], which writes the character's ahoy `CharacterLook` (what
//! the KCC steers by) and the replicated [`LookDirection`] (where other clients see the
//! character facing). Nothing accumulates look deltas, so a lost or altered tick is corrected
//! by the next one instead of becoming a permanent offset.

use crate::combat::Dead;
use bevy::prelude::*;
use bevy_ahoy::CharacterLook;
use bevy_ahoy::input::{Jump, Movement};
use lightyear::prelude::client::InputDelayConfig;
use lightyear::prelude::{AppComponentExt, InputTimelineConfig};
use lightyear_inputs_bei::prelude::*;
use serde::{Deserialize, Serialize};

/// The replicated BEI input context for the player character — carried by the character entity
/// itself (ahoy's input observers write the *context entity's* `AccumulatedInput`, and its KCC
/// runs on the entity carrying `CharacterController`; ahoy requires both to be the same
/// entity). Spawned server-side in `player()`; the owning client binds real inputs to the
/// replicated action entities.
///
/// The bounds beyond `Component` (`PartialEq`/`Clone`/`Debug`/serde/`TypePath`) are
/// `InputPlugin`'s own requirements, since the context entity is replicated. `TypePath` is
/// NOT auto-generated by `derive(Component)` in Bevy 0.19 — it's derived explicitly here.
#[derive(Component, TypePath, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlayerInputContext;

/// The owning client's absolute look direction as `Vec2(yaw, pitch)` in radians, in ahoy's
/// `CharacterLook` convention: yaw about +Y, 0 facing −Z, positive turning left; pitch positive
/// looking up. Not bound to any device: the client sets it every tick from its camera through
/// a persistent `ActionMock` (`p19_client::controls`), so it rides the replicated input stream
/// (tick-aligned, input-delayed and rolled back exactly like `Movement`).
#[derive(Debug, InputAction)]
#[action_output(Vec2)]
pub struct Look;

/// Where a character is looking — the last [`Look`] input the server accepted. Replicated, so
/// other clients can orient the character's model (and later aim, animation). Written only by
/// [`apply_look`]; unlike ahoy's `CharacterLook`, nothing in the physics stack touches it.
#[derive(Component, Reflect, Clone, Copy, Debug, Default, PartialEq, Serialize, Deserialize)]
#[reflect(Component)]
pub struct LookDirection {
    /// Radians about +Y, wrapped to `[-π, π)`; 0 faces −Z.
    pub yaw: f32,
    /// Radians, clamped to `±`[`MAX_LOOK_PITCH`]; positive looks up.
    pub pitch: f32,
}

/// Pitch limit, just short of straight up/down (ahoy's own camera uses the same margin).
pub const MAX_LOOK_PITCH: f32 = core::f32::consts::FRAC_PI_2 - 0.01;

impl LookDirection {
    /// Validates a client-sent `(yaw, pitch)`: `None` if either is not finite, otherwise yaw
    /// wrapped and pitch clamped. The server never trusts client input beyond this shape.
    pub fn from_input(value: Vec2) -> Option<Self> {
        if !value.is_finite() {
            return None;
        }
        let tau = core::f32::consts::TAU;
        Some(Self {
            yaw: (value.x + core::f32::consts::PI).rem_euclid(tau) - core::f32::consts::PI,
            pitch: value.y.clamp(-MAX_LOOK_PITCH, MAX_LOOK_PITCH),
        })
    }
}

/// Applies the owning client's [`Look`] input to its character (server: every player; client:
/// its own, which is what the predicted KCC and its rollback replay steer by). The KCC reads
/// `CharacterLook` in `FixedPostUpdate`, after this runs in `FixedPreUpdate`'s input phase.
/// ahoy's `spin_character_look` (rotating the look with a spinning floor) still edits
/// `CharacterLook` between ticks; the next tick's input overwrites it.
fn apply_look(
    look: On<Fire<Look>>,
    mut characters: Query<(&mut LookDirection, &mut CharacterLook), Without<Dead>>,
) {
    let Ok((mut direction, mut character_look)) = characters.get_mut(look.context) else {
        return;
    };
    let Some(new_direction) = LookDirection::from_input(look.value) else {
        return;
    };
    direction.set_if_neq(new_direction);
    character_look.yaw = new_direction.yaw;
    character_look.pitch = new_direction.pitch;
}

/// Registers the [`lightyear_inputs_bei`] input protocol (context + action types) on both
/// binaries, next to [`SharedReplicationPlugin`](crate::replication::SharedReplicationPlugin)
/// in each one's plugin list.
pub struct SharedInputsPlugin;

impl Plugin for SharedInputsPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(InputPlugin::<PlayerInputContext>::default())
            // Every ahoy action type whose action entities must replicate: the `Action<A>`
            // component registration is what recreates the correctly-typed action entity on
            // the receiver (its live state travels via `BEIStateSequence` messages, not via
            // this registration).
            .register_input_action::<Movement>()
            .register_input_action::<Jump>()
            .register_input_action::<Look>()
            .add_observer(apply_look);
        app.component::<LookDirection>().replicate();
        // The client must LEAD the server's timeline by enough ticks that its tick-N input
        // arrives before the server simulates tick N — `InputTimelineConfig::default()` is
        // `no_input_delay()`, which made every input arrive ~3 ticks after the server had
        // already simulated it (`server_late_input_mismatch` corrections: the server applied
        // wrong-tick look deltas and movement, fighting the client's prediction — "can only
        // move one direction at certain look angles"). `balanced()` covers up to ~50ms of
        // latency with input delay (auto-recomputed from RTT; insertion also triggers that
        // recompute) and beyond that uses prediction.
        //
        // `minimum_input_delay_ticks: 2` — NOT the preset's 0: the auto-computed delay is
        // `ceil(RTT/tick)`, which is ~0 on loopback, but the send happens in PostUpdate and
        // lands next tick's PreUpdate — a structural 1-tick lateness no RTT measurement
        // reports. Harmless for state-based input, but look input is delta-accumulated
        // server-side (`p19_server::input`), and wrong-tick deltas corrupt the accumulation and
        // fight the prediction. A 2-tick floor (~33ms) guarantees the lead covers scheduling.
        app.insert_resource(InputTimelineConfig::default().with_input_delay(InputDelayConfig {
            minimum_input_delay_ticks: 2,
            ..InputDelayConfig::balanced()
        }));
    }
}
