//! The player input protocol: a BEI context + ahoy action types, replicated via
//! `lightyear_inputs_bei`.
//!
//! This is the M2 "idiomatic" flow (see `docs/adr/0005`'s follow-up plan): the **server**
//! spawns the input context + its action entities as part of the player bundle (`player()`),
//! they replicate to the owning client (via `ActionOf<C>`'s hierarchy sender), the owning
//! client adds local-only `Bindings` to the replicated action entities (see
//! `controls.rs`'s binding observers), and from then on the client's BEI action state streams
//! to the server as `BEIStateSequence` messages, which mock the server-side actions — so
//! ahoy's observers fire on **both** sides and both run the same KCC over the same input.
//!
//! lightyear's `PredictionPlugin` hard-depends on one of its input plugins
//! (`lightyear_inputs_native`/`_bei`/`_leafwing`) having initialized `LastConfirmedInput` —
//! without one, the client panics ("Resource does not exist: LastConfirmedInput") the moment
//! a connection starts. Registering [`InputPlugin`] here satisfies that (with the
//! `input_bei` meta-crate feature — see the root `Cargo.toml` comment).
//!
//! This lives in `shared`, not either binary, for the same reason `replication.rs` does: the
//! input protocol (`BEIStateSequence<C>` messages, replicated context/action entities) is
//! network state both sides must agree on. Each binary enables its own `client`/`server`
//! feature on the `lightyear_inputs_bei` dependency; feature unification applies whichever
//! subset is active to this crate's build.

use bevy::prelude::*;
use bevy_ahoy::input::{Jump, Movement, RotateCamera};
use lightyear::prelude::client::InputDelayConfig;
use lightyear::prelude::{AppComponentExt, InputTimelineConfig};
use lightyear_inputs_bei::prelude::*;
use serde::{Deserialize, Serialize};

/// The replicated BEI input context for the player character — carried by the character entity
/// itself (ahoy's input observers write the *context entity's* `AccumulatedInput`, and its KCC
/// runs on the entity carrying `CharacterController`; ahoy requires both to be the same
/// entity). Spawned server-side in `player()`; the owning client binds real inputs to the
/// replicated action entities.
///
/// The bounds beyond `Component` (`PartialEq`/`Clone`/`Debug`/serde/`TypePath`) are
/// `InputPlugin`'s own requirements, since the context entity is replicated. `TypePath` is
/// NOT auto-generated by `derive(Component)` in Bevy 0.19 — it's derived explicitly here.
#[derive(Component, TypePath, Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct PlayerInputContext;

/// Marks the mouse-look `RotateCamera` action entity (per-replicated-entity device distinction,
/// same idea as the legacy `GamepadLook` marker): the mouse binding scales by radians-per-pixel,
/// the stick binding by radians-per-second — different per-device scaling is why look input is
/// TWO action entities (action-level modifiers hit all of an action's bindings uniformly, and
/// BEI presets like `Axial` can't be nested inside per-binding `Spawn(...)`).
#[derive(Component, Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct MouseLook;

/// Marks the gamepad-stick-look `RotateCamera` action entity — see [`MouseLook`].
#[derive(Component, Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
pub struct StickLook;

/// Registers the [`lightyear_inputs_bei`] input protocol (context + action types) on both
/// binaries, next to [`SharedReplicationPlugin`](crate::replication::SharedReplicationPlugin)
/// in each one's plugin list.
pub struct SharedInputsPlugin;

impl Plugin for SharedInputsPlugin {
    fn build(&self, app: &mut App) {
        app.add_plugins(InputPlugin::<PlayerInputContext>::default())
            // Every ahoy action type whose action entities must replicate: the `Action<A>`
            // component registration is what recreates the correctly-typed action entity on
            // the receiver (its live state travels via `BEIStateSequence` messages, not via
            // this registration).
            .register_input_action::<Movement>()
            .register_input_action::<Jump>()
            .register_input_action::<RotateCamera>();
        // The look-device markers ride the same replicated action entities so the owning
        // client's binding observers can tell them apart. (Separate statements — `.replicate()`
        // returns a registration builder, not the `App`.)
        app.component::<MouseLook>().replicate();
        app.component::<StickLook>().replicate();
        // The client must LEAD the server's timeline by enough ticks that its tick-N input
        // arrives before the server simulates tick N — `InputTimelineConfig::default()` is
        // `no_input_delay()`, which made every input arrive ~3 ticks after the server had
        // already simulated it (`server_late_input_mismatch` corrections: the server applied
        // wrong-tick look deltas and movement, fighting the client's prediction — "can only
        // move one direction at certain look angles"). `balanced()` covers up to ~50ms of
        // latency with input delay (auto-recomputed from RTT; insertion also triggers that
        // recompute) and beyond that uses prediction.
        //
        // `minimum_input_delay_ticks: 2` — NOT the preset's 0: the auto-computed delay is
        // `ceil(RTT/tick)`, which is ~0 on loopback, but the send happens in PostUpdate and
        // lands next tick's PreUpdate — a structural 1-tick lateness no RTT measurement
        // reports. Harmless for state-based input, but look input is delta-accumulated
        // server-side (`server::input`), and wrong-tick deltas corrupt the accumulation and
        // fight the prediction. A 2-tick floor (~33ms) guarantees the lead covers scheduling.
        app.insert_resource(InputTimelineConfig::default().with_input_delay(InputDelayConfig {
            minimum_input_delay_ticks: 2,
            ..InputDelayConfig::balanced()
        }));
    }
}
